const ShopActionTypes = {
  FETCH_COLLECTIONS_START: "FETCHING_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCHING_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCHING_COLLECTIONS_FAILURE"
};

export default ShopActionTypes;
